### PR TITLE
Use `latestworld-if-toplevel`

### LINKED ISSUE #58: `World age increment not at top level` regression with v1.3.1
It looks like something might have regressed in 1.3.1 (works with 1.3.0; but also still broken with current master, i.e. 6b5623a60f6e8dfa4635dc597653474882aa8321).

The MWE is a bit weird, so maybe this is actually not supposed to work, but it shows up in the real world in HTTP.jl, which currently fails to precompile on 1.12 and above: https://github.com/JuliaWeb/HTTP.jl/blob/9db9aaded7c942e442b185d03ea5fd212b1b7efe/src/precompile.jl#L34-L38

The following MWE

```julia
hello(who::String) = "Hello, $who"
using PrecompileTools: @setup_workload, @compile_workload
@setup_workload begin
    withenv() do
        @compile_workload begin
            hello("x")
        end
    end
end
```

leads to 

```
ERROR: LoadError: syntax: World age increment not at top level
Stacktrace:
 [1] top-level scope
   @ ~/oss/Example.jl/src/Example.jl:19
 [2] include(mod::Module, _path::String)
   @ Base ./Base.jl:303
 [3] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::Nothing)
   @ Base ./loading.jl:3019
 [4] top-level scope
   @ stdin:5
 [5] eval(m::Module, e::Any)
   @ Core ./boot.jl:489
 [6] include_string(mapexpr::typeof(identity), mod::Module, code::String, filename::String)
   @ Base ./loading.jl:2865
 [7] include_string
   @ ./loading.jl:2875 [inlined]
 [8] exec_options(opts::Base.JLOptions)
   @ Base ./client.jl:329
 [9] _start()
   @ Base ./client.jl:563
in expression starting at /home/mortenpi/oss/Example.jl/src/Example.jl:1
in expression starting at stdin:
```

Only affects Julia 1.12+ (getting it on `1.12.0-beta1` and `1.13.0-DEV.361`), since <= 1.11 installs PrecompileTools 1.2.1.

### PR DESCRIPTION
**Pull request by timholy**
Fixes #58

### CODE REVIEW

File: test/runtests.jl [hunk 1]
```diff
@@ -87,6 +87,18 @@ using Base: specializations
...
+    # Check that calls inside @setup_workload are not precompiled
+    m = NotToplevel.NotPrecompiled.themethod
+    have_char = have_float = false
+    for mi in specializations(m)
+        mi === nothing && continue
+        have_char |= mi.specTypes.parameters[2] === Char
+        have_float |= mi.specTypes.parameters[2] === Float64
+    end
+    @test !have_float       # not wrapped inside `@compile_workload`
+    @test_broken have_char  # is wrapped
```
Comment (timholy) [inline test/runtests.jl:100]: @mortenpi @benlorenz note that the pattern used in your reports blocks effective precompilation. If you haven't followed, here's the issue: if you compile external (outside of the package, e.g., Base or whatever) code before you reach `@compile_workload`, it will not be cached. The problem is that your construct forces compilation of the anonymous function before `@compile_workload` turns on. Thus, any code not "owned" by your package that can't be inferrably traced back to a caller in your package will be dropped from the precompile cache.

As a guide to understanding the test, know that `Base.inferencebarrier` is used in `NotPrecompiled` to force runtime dispatch.

Comment (timholy) [reply test/runtests.jl:100]: Also CC @jpthiele

**Comment by jpthiele** [comment]
I added this branch manually to my local nightly version and was able to precompile HTTP.

**Comment by jpthiele** [comment]
But switching `@compile_workload` and `withenv` fixes the problem as well, see https://github.com/JuliaWeb/HTTP.jl/pull/1219

**Comment by timholy** [comment]
I've added a warning to the documentation about avoiding this `withenv(...) do @compile_workload begin ... end end` pattern. Even though it doesn't error in this PR, it's self-defeating.

In case someone gets to this before me, I've tagged this `merge me`.
