### PR TITLE
Ensure compilation happens after logging starts

### LINKED ISSUE #17: Understand why `let` wrapping the compile workload can lead to worse latency
This was observed in https://github.com/JuliaLang/PrecompileTools.jl/pull/16. It would be good to understand the interaction with `let` here since ideally, it would be good to keep it.

### LINKED ISSUE #26: Still have some compilation time
Hi,
It seems as PrecompileTools does not "work" in the following case. By that I mean that compilatiin still hqppen before running the function. Please see below:

```julia
module MSort

using PrecompileTools

function quicksort(
    v::Vector{T};
    lo::Int = 1,
    hi::Int = length(v),
) where {T <: Union{Int64, Float64}}
    x = copy(v) 
    quick!(x, lo, hi)
    x
end

function partition(
    xp::Vector{T},
    pivot::T,
    left::Int,
    right::Int,
) where {T <: Union{Int64, Float64}}
    while left <= right
        while xp[left] < pivot
            left += 1
        end
        while pivot < xp[right]
            right -= 1
        end
        if left <= right
            xp[left], xp[right] = xp[right], xp[left]
            left += 1
            right -= 1
        end
    end
    left, right
end

function quick!(
    xp::Vector{T},
    i::Int,
    j::Int,
) where {T <: Union{Int64, Float64}}
    if j > i
        left, right = partition(xp, xp[(j+i)>>>1], i, j)
        quick!(xp, i, right)
        quick!(xp, left, j)
    end
end

@setup_workload begin 
    @compile_workload begin
        quicksort(rand(64))
    end
end

end

x = rand(64); @time Msort.quicksort(x);
# 0.004929 seconds (29 allocations: 2.047 KiB, 99.56% compilation time)
```
However if I replace `Vector{T}` by `Vector{Float64}`, and remove all `T` in the code, then it works.

Is that expected that compilation happen in the first version ?
If yes, could we have PrecompileTools work with parametric type? If no, I suppose it is a bug?

Thank you

### LINKED ISSUE #37: `@compile_workload` fails to compile some explicit toplevel calls
When I put setup in `@compile_workload`, it fails to compile later steps. I suspect this is due to inlining or otherwise treating multiple lines in the compile workflow step as a single operation.

Does not compile `rand(::AliasTable)`
```julia
PrecompileTools.@compile_workload begin
    at = AliasTable([1.0, 2.0])
    rand(at)
end
```

Does compile `rand(::AliasTable)`
```julia
at = AliasTable([1.0, 2.0])
PrecompileTools.@compile_workload begin
    rand(at)
end
```

Full example

```
x@fedora:~/.julia/dev/AliasTables$ cat src/AliasTables.jl 
module AliasTables

using Random
using PrecompileTools

export AliasTable

struct AliasTable{T}
    x::T
end
Base.rand(x::AliasTable) = rand(x.x)

at = AliasTable([1.0, 2.0])
PrecompileTools.@compile_workload begin
    rand(at)
end

end
x@fedora:~/.julia/dev/AliasTables$ julia --project -e '@time using AliasTables; @time at = AliasTable([1.0, 2.0]); @time rand(at)'
Precompiling AliasTables...
  1 dependency successfully precompiled in 1 seconds. 6 already precompiled.
  1.115552 seconds (599.80 k allocations: 35.161 MiB, 38.56% compilation time)
  0.000001 seconds (4 allocations: 112 bytes)
  0.000016 seconds (7 allocations: 320 bytes)
x@fedora:~/.julia/dev/AliasTables$ julia --project -e '@time using AliasTables; @time at = AliasTable([1.0, 2.0]); @time rand(at)'
  0.022336 seconds (37.92 k allocations: 2.467 MiB)
  0.000002 seconds (4 allocations: 112 bytes)
  0.000011 seconds (7 allocations: 320 bytes)
x@fedora:~/.julia/dev/AliasTables$ git checkout HEAD~
HEAD is now at 87e8d9c Broken
x@fedora:~/.julia/dev/AliasTables$ cat src/AliasTables.jl 
module AliasTables

using Random
using PrecompileTools

export AliasTable

struct AliasTable{T}
    x::T
end
Base.rand(x::AliasTable) = rand(x.x)

PrecompileTools.@compile_workload begin
    at = AliasTable([1.0, 2.0])
    rand(at)
end

end
x@fedora:~/.julia/dev/AliasTables$ julia --project -e '@time using AliasTables; @time at = AliasTable([1.0, 2.0]); @time rand(at)'
Precompiling AliasTables...
  1 dependency successfully precompiled in 1 seconds. 6 already precompiled.
  0.994406 seconds (598.94 k allocations: 35.113 MiB, 43.08% compilation time)
  0.000002 seconds (4 allocations: 112 bytes)
  0.002649 seconds (236 allocations: 11.422 KiB, 99.55% compilation time)
x@fedora:~/.julia/dev/AliasTables$ julia --project -e '@time using AliasTables; @time at = AliasTable([1.0, 2.0]); @time rand(at)'
  0.022320 seconds (37.92 k allocations: 2.467 MiB)
  0.000001 seconds (4 allocations: 112 bytes)
  0.002591 seconds (236 allocations: 11.422 KiB, 99.63% compilation time)
```

I ran into this example when attempting to use this package to set up precompilation for AliasTables.jl (https://github.com/LilithHafner/AliasTables.jl/pull/33)

### PR DESCRIPTION
**Pull request by timholy**
If compilation of the workload happens before the logging system is
initialized, many CodeInstances may be missed. This exploits
`Core.@latestworld` to prevent inference from proceeding into the
workload. It removes the `@force_compile`, which introduces
some risk that even the workload will be interpreted.

Also wraps the `@setup_workload` block with a `let`.

Fixes #17
Fixes #26
Fixes #37
Closes #40
Closes https://github.com/JuliaLang/julia/issues/57957

CC @vtjnash

### CODE REVIEW

**Comment by timholy** [comment]
Weird. Those tests pass locally for me. I'm guessing it's a coverage thing.

**Comment by KristofferC** [comment]
Is there something that can be backported to a pre-1.12+ julia PrecompileTools version so that the compile fixes are also available there?

**Comment by timholy** [comment]
No, `Core.@invokelatest` was only added in Julia 1.12.

**Comment by timholy** [comment]
Yes I meant `Core.@latestworld`, sorry. I doubt the `@invokelatest` would help.

**Comment by timholy** [comment]
I could add a branch for pre-Julia 1.12 to make it easier to continue to support older releases. Since this repo is JuliaLang, any preferred naming convention?

**Comment by vtjnash** [comment]
Before v1.12, you could conditionally define something like `macro latestworld() esc(Expr(:toplevel, nothing)) end` to attempt to influence the heuristics (or perhaps `Expr(:copyast, nothing)` if forced toplevel is too strong)

File: test/without_coverage.jl [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+
+    push!(LOAD_PATH, @__DIR__)
+
+    using MSort
+    using AliasTables
+    x = rand(64)
+    pipe = Pipe()
+    oldstderr = stderr
+    redirect_stderr(pipe)
+    @trace_compile begin
```
Comment (KristofferC) [inline test/without_coverage.jl:16]: You have to be a bit careful here with the exact same thing this PR attempts to fix, that Julia doesn't compile the code in the `begin` block before the tracing has been enabled (as discussed in https://github.com/JuliaLang/julia/issues/57899). So maybe there should be an `@eval` here or something like that?

Comment (KristofferC) [reply test/without_coverage.jl:16]: It might work because (AFAIU), `@testset` has special code to insert world age bumps between statements, or something to that effect. Or because of some other completely different reason... 🤷
